assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

    bundles: [ 'JDareClankBundle', 'BakalavrBundle' ]
    assets:
        css:
            inputs:
#                - 'bower_components/bootstrap/dist/css/bootstrap.min.css'
#                - 'css/reset.css'
#                - 'css/style.css'
        vendor:
            inputs:
                - 'bower_components/jquery/dist/jquery.min.js'
#                - 'bower_components/bootstrap/dist/js/bootstrap.min.js'
                - 'bower_components/angular/angular.js'
                - 'bower_components/angular-ui-router/release/angular-ui-router.min.js'
                - 'bower_components/angular-sanitize/angular-sanitize.min.js'
                - 'bower_components/videogular/videogular.min.js'
                - 'bower_components/videogular-controls/vg-controls.min.js'
                - 'src/jqueryIndex.js'

        custom:
            inputs:
                - 'src/app.js'
                - 'src/service/*'
                - 'src/controller/*'
                - 'src/directive/*'